/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function _compileTargetSuffix(): string

export declare function _run(input: NativeRunOptions, helper: string): Promise<NativeRunReport>

export declare function _runCli(argv: Array<string>, helper: string): Promise<number>

export declare function canonicalStem(value: string): string

export interface NativeRunOptions {
  path: string
  output: string
  apiUrl?: string
  method?: string
  backend?: string
  effort?: string
  lang?: string
  url?: string
  start?: number
  end?: number
  formula?: boolean
  table?: boolean
  imageAnalysis?: boolean
  clientSideOutputGeneration?: boolean
}

export interface NativeRunReport {
  warnings: Array<string>
}

export declare function validatePdfOptions(startPage: number, endPage: number | undefined | null, formulaEnable: boolean, tableEnable: boolean, imageAnalysis: boolean): boolean
