/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Sanitize an output stem through the canonical portable-name validator. */
export declare function canonicalStem(s: string): string

/**
 * Validate official PDF option bounds (start/end page, workers, limits).
 *
 * `start` is zero-based; `end` is inclusive or `null`. Returns `true` on valid
 * bounds and throws with the underlying diagnostic otherwise.
 */
export declare function validatePdfOptions(startPage: number, endPage: number | undefined | null, formulaEnable: boolean, tableEnable: boolean, imageAnalysis: boolean): boolean
